- cmd: cd $WHERE_THE_BAG_STORE
  on_fail: retry
- cmd: ds-rosbag-scan-multi ~/out
  on_fail: retry
- cmd: ds-rosbag-import
  on_fail: retry
- cmd: cd ~/out
  on_fail: retry
- cmd: ds-compress-video
  on_fail: retry
- cmd: ds-check
  on_fail: retry
- cmd: cp -r * ~/datasets_writable
  on_fail: retry
- cmd: ds-submit
  on_fail: retry
