- cmd: cd $WHERE_THE_BAG_STORE
  on_fail: retry
- cmd: ds-rosbag-scan ./out
  on_fail: retry
- cmd: tmux
  on_fail: retry
- cmd: ds-rosbag-scan ./out | xargs -L1 -P4 ds-import | tee import-log.log
  on_fail: retry
- cmd: cd out
  on_fail: retry
- cmd: ls | xargs -L1 ds-compress-video
  on_fail: retry
- cmd: ls | xargs -L1 ds-check
  on_fail: retry
- cmd: cp -r * ~/datasets_writable
  on_fail: retry
- cmd: ls | xargs -L1 ds-submit
  on_fail: retry
